customer_segmentation:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 17 for SQL Server"
      server: ANHKHOA\SQLEXPRESS
      port: 1433
      database: kpimbank
      schema: dbo
      windows_login: true
      threads: 1
      encrypt: true
      trust_cert: true